repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: poetry run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: Ruff format
        entry: poetry run ruff format --check
        language: system
        types: [python]

      - id: pytest
        name: Pytest
        entry: poetry run pytest -q
        language: system
        pass_filenames: false
